import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
// Loading the styles for Font Awesome components in the root layout prevents it
// from loading initial styles (inappropriately large icons)
import "@fortawesome/fontawesome-svg-core/styles.css";
import { CartContextProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <CartContextProvider>{children}</CartContextProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
